import type {
  Difficulty,
  GameSettings,
  WorldState,
  Stats,
  WorldRules,
} from "../core/types";
import { addItem, newInventory } from "./inventory";
import { WorldGenerator } from "../world/generator";
import { initialDirector, initialNarrative } from "./quality-state";
export function initialStats(): Stats {
  return {
    oxygen: 100,
    health: 100,
    blood: 100,
    stamina: 100,
    energy: 82,
    hydration: 78,
    temperature: 36.8,
    fatigue: 8,
    wetness: 0,
    pain: 0,
    bleeding: 0,
    fracture: false,
    infection: 0,
    poison: 0,
  };
}
export function createWorld(
  seed: string,
  name = "灰谷生存记录",
  difficulty: Difficulty = "standard",
  rules: Partial<WorldRules> = {},
): WorldState {
  const gen = new WorldGenerator(seed),
    inv = newInventory();
  for (const [id, count] of Object.entries({
    knife: 1,
    water: 1,
    backpack: 1,
    jacket: 1,
    pants: 1,
    boots: 1,
  }))
    addItem(inv, id, count);
  const knife = inv.items.find((i) => i.id === "knife")!.uid;
  return {
    version: 2,
    waypoint: null,
    cooldowns: {},
    rules: {
      dayLength: rules.dayLength ?? 60,
      lootAmount: rules.lootAmount ?? 1,
      enemyDensity: rules.enemyDensity ?? 1,
      permadeath: difficulty === "ashfall" || (rules.permadeath ?? false),
    },
    seed,
    name,
    difficulty,
    createdAt: Date.now(),
    elapsed: 0,
    time: 15.4,
    day: 1,
    weather: "cloudy",
    nextWeather: 240,
    uidCounter: 0,
    player: {
      position: gen.position(-14, -28),
      yaw: 0.18,
      pitch: 0,
      stats: initialStats(),
      inventory: inv,
      equipment: {
        primary: knife,
        back: inv.items.find((i) => i.id === "backpack")!.uid,
        chest: inv.items.find((i) => i.id === "jacket")!.uid,
        legs: inv.items.find((i) => i.id === "pants")!.uid,
        feet: inv.items.find((i) => i.id === "boots")!.uid,
      },
      quickSlots: [knife, null, null, null, null],
      selected: 0,
      flashlight: false,
      flashlightCharge: 100,
      stance: "stand",
      spawn: gen.position(-14, -28),
      vehicle: null,
      kills: 0,
      deaths: 0,
      distance: 0,
    },
    containers: {},
    actors: {},
    structures: [],
    vehicles: [],
    doors: {},
    doorStates: {},
    narrative: initialNarrative(),
    director: initialDirector(),
    destroyed: [],
    discovered: [],
    journal: ["crash"],
    flags: [],
    events: [],
    nextEvent: 180,
    ended: false,
  };
}
export const DEFAULT_SETTINGS: GameSettings = {
  quality: "high",
  resolution: 1,
  fov: 60,
  cameraProfile: 1,
  sensitivity: 1,
  invertY: false,
  dragLook: false,
  headBob: 0.35,
  cameraShake: 0.5,
  masterVolume: 0.65,
  ambientVolume: 0.55,
  effectsVolume: 0.7,
  uiScale: 1,
  subtitles: true,
  reducedMotion: false,
  fullscreen: false,
  keys: {
    forward: "KeyW",
    backward: "KeyS",
    left: "KeyA",
    right: "KeyD",
    interact: "KeyE",
    sprint: "ShiftLeft",
    walk: "AltLeft",
    jump: "Space",
    crouch: "ControlLeft",
    prone: "KeyZ",
    inventory: "Tab",
    crafting: "KeyC",
    building: "KeyB",
    map: "KeyM",
    journal: "KeyJ",
    reload: "KeyR",
    flashlight: "KeyF",
    grenade: "KeyG",
    leanLeft: "KeyQ",
    leanRight: "KeyV",
  },
};
export const DIFFICULTIES = {
  survivor: {
    name: "幸存者",
    description: "资源较多，伤害与生存消耗较低。适合初次进入灰谷。",
    damage: 0.6,
    drain: 0.65,
    permadeath: false,
  },
  standard: {
    name: "标准",
    description: "有限的补给，真实的威胁。准备、探索与撤退同样重要。",
    damage: 1,
    drain: 1,
    permadeath: false,
  },
  hardcore: {
    name: "硬核",
    description: "伤害加重，资源更紧张。死亡后仅保留营地与世界。",
    damage: 1.5,
    drain: 1.4,
    permadeath: false,
  },
  ashfall: {
    name: "灰烬",
    description: "最高生存压力。只有一次生命，死亡后该世界无法继续。",
    damage: 1.8,
    drain: 1.7,
    permadeath: true,
  },
} as const;
