import type { Recipe } from "../core/types";
import { anchor } from "./sequences";
import type { NarrativeAnchor } from "./types";

export interface NarrativeInteractionDefinition {
  id: string;
  title: string;
  description: string;
  kind:
    "npc" | "supplies" | "terminal" | "radio" | "shelter" | "lift" | "choice";
  anchor: NarrativeAnchor;
  audioId?: string;
  npc?: string;
  questId?: string;
  stage?: number;
}
export interface SideQuestDefinition {
  id: string;
  title: string;
  synopsis: string;
  steps: {
    interaction: string;
    objective: string;
    cost?: Record<string, number>;
  }[];
  reward: Record<string, number>;
  unlockRecipe?: string;
  unlockRoute?: string;
}
const node = (
  id: string,
  title: string,
  description: string,
  kind: NarrativeInteractionDefinition["kind"],
  poiId: string,
  x = 0,
  y = 0,
  z = -2,
  audioId?: string,
  npc?: string,
): NarrativeInteractionDefinition => ({
  id,
  title,
  description,
  kind,
  anchor: anchor(poiId, x, y, z),
  audioId,
  npc,
});

export const NARRATIVE_INTERACTIONS: NarrativeInteractionDefinition[] = [
  node(
    "ranger-supplies",
    "林务员留下的补给",
    "取得罐头和水，先解决今晚的食物。",
    "supplies",
    "pine-0",
    -2,
    0,
    -2,
  ),
  node(
    "ranger-shelter",
    "林务站安全点",
    "关好门，设置新的复活位置。附近有威胁时无法建立安全点。",
    "shelter",
    "pine-0",
    2,
    0,
    -2,
  ),
  node(
    "ranger-radio",
    "接通林务站接收机",
    "比对撤离循环广播与林务员今天的录音。",
    "radio",
    "pine-0",
    0,
    0,
    2,
    "ranger-warning",
  ),
  node(
    "medical-record",
    "询问米拉：转运名单",
    "核验病历和受试批次。",
    "npc",
    "pine-1",
    -2,
    0,
    -2,
    "mira-cases",
    "米拉",
  ),
  node(
    "military-record",
    "撤防命令与访问卡",
    "军方把居民改称样本。取走访问卡。",
    "terminal",
    "fort-1",
    0,
    0,
    -2,
    "military-order",
  ),
  node(
    "contractor-record",
    "衡川第七批次货单",
    "事故前两年就获批的适应舱和清理燃料。",
    "terminal",
    "industry-0",
    0,
    0,
    -2,
    "contractor-ledger",
  ),
  node(
    "missing-record",
    "市立医院转运簿",
    "失踪居民并未离城，转运终点是 R-07。",
    "terminal",
    "city-1",
    0,
    0,
    -2,
    "missing-voices",
  ),
  node(
    "mayor-record",
    "市政原始会议录音",
    "公开档案需要这份独立证词。",
    "terminal",
    "city-4",
    0,
    0,
    -2,
    "mayor-session",
  ),
  node(
    "ashfall-decode",
    "比对 ASHFALL 命令",
    "需要医疗、军方、承包商和失踪者四份记录。",
    "terminal",
    "fort-4",
  ),
  node(
    "facility-enter",
    "进入地下研究设施",
    "访问卡通过后乘升降台到地下八米。",
    "lift",
    "lab-0",
    0,
    0,
    -7,
  ),
  node(
    "facility-exit",
    "返回地面",
    "乘升降台返回研究站入口。",
    "lift",
    "lab-0",
    0,
    -8,
    -3,
  ),
  node(
    "facility-military",
    "军方联络终端",
    "核验军方的目标与责任。",
    "terminal",
    "lab-0",
    -3,
    -8,
    -2,
    "facility-military",
  ),
  node(
    "facility-research",
    "研究员原始观察记录",
    "核验失败的人体适应实验。",
    "terminal",
    "lab-0",
    3,
    -8,
    -2,
    "facility-research",
  ),
  node(
    "facility-government",
    "地方协调会议终端",
    "核验医院补贴、健康数据与虚假的安置人数。",
    "terminal",
    "lab-0",
    -3,
    -8,
    2,
    "facility-government",
  ),
  node(
    "facility-contractor",
    "承包商控制回路终端",
    "核验清理回路的设计和手动隔离方式。",
    "terminal",
    "lab-0",
    3,
    -8,
    2,
    "facility-contractor",
  ),
  node(
    "facility-archive",
    "复制完整原始档案",
    "需要核验地下四个终端。",
    "terminal",
    "lab-0",
    0,
    -8,
    2,
  ),
  node(
    "facility-isolate",
    "切断谷地清理回路",
    "隔离地表燃料管线，使焚毁只限于地下样本库。",
    "terminal",
    "lab-0",
    3,
    -8,
    0,
  ),
  node(
    "facility-control",
    "最终控制台",
    "检查可用选择及其后果。",
    "terminal",
    "lab-0",
    0,
    -8,
    3,
  ),
  node(
    "choice-publish",
    "公开档案与证词 · Truth",
    "把完整证据送出封锁区，让幸存者有姓名。",
    "choice",
    "lab-0",
    -1,
    -8,
    3,
  ),
  node(
    "choice-destroy",
    "隔离并销毁 · Ash",
    "烧掉地下样本和原始档案，阻止第二批实验。",
    "choice",
    "lab-0",
    0,
    -8,
    3,
  ),
  node(
    "choice-shutdown",
    "关闭系统并留下 · Survivor",
    "切断远程清理，留下维护低温与隔离系统。",
    "choice",
    "lab-0",
    1,
    -8,
    3,
  ),
  node(
    "doctor-request",
    "米拉：没有回来的医生",
    "接受寻找韩医生的委托。",
    "npc",
    "pine-1",
    -2,
    0,
    -2,
    "doctor-request",
    "米拉",
  ),
  node(
    "doctor-found",
    "为韩医生包扎",
    "带两卷绷带到矿场诊所。",
    "npc",
    "mine-5",
    0,
    0,
    -2,
    "doctor-found",
    "韩医生",
  ),
  node(
    "doctor-return",
    "把转院底单交给米拉",
    "韩医生的证据与诊所记录可以互相核验。",
    "npc",
    "pine-1",
    -2,
    0,
    -2,
    "doctor-return",
    "米拉",
  ),
  node(
    "hunter-request",
    "罗岚：湖边的家人",
    "沿三道斜杠去林边住宅寻找猎人家属。",
    "npc",
    "lake-2",
    0,
    0,
    -2,
    "hunter-request",
    "罗岚",
  ),
  node(
    "hunter-route",
    "给许禾母子送食物和水",
    "需要炖肉罐头和饮用水各一份。",
    "npc",
    "pine-9",
    0,
    0,
    -2,
    "hunter-route",
    "许禾",
  ),
  node(
    "hunter-return",
    "告诉罗岚家人的路线",
    "带回许禾的巡林路线。",
    "npc",
    "lake-2",
    0,
    0,
    -2,
    "hunter-return",
    "罗岚",
  ),
  node(
    "checkpoint-request",
    "阿衡：没有发出的口粮",
    "去后勤仓库找未开启的封条。",
    "npc",
    "fort-6",
    0,
    0,
    -2,
    "checkpoint-request",
    "阿衡",
  ),
  node(
    "checkpoint-proof",
    "取回后勤封条",
    "核验仍未分发的救援物资。",
    "terminal",
    "fort-5",
    0,
    0,
    -2,
    "checkpoint-proof",
  ),
  node(
    "checkpoint-return",
    "把封条交给阿衡",
    "打开检查站侧门并取得背心。",
    "npc",
    "fort-6",
    0,
    0,
    -2,
    "checkpoint-return",
    "阿衡",
  ),
  node(
    "raider-request",
    "陈娅：一锅人的份量",
    "带两罐豆子去工业区和唐砾谈判。",
    "npc",
    "city-5",
    0,
    0,
    -2,
    "raider-request",
    "陈娅",
  ),
  node(
    "raider-deal",
    "和唐砾达成分水约定",
    "交付两罐豆子，换回滤芯与停战约定。",
    "npc",
    "industry-6",
    0,
    0,
    -2,
    "raider-deal",
    "唐砾",
  ),
  node(
    "raider-return",
    "交回滤芯与约定",
    "陈娅将为工业区幸存者分水。",
    "npc",
    "city-5",
    0,
    0,
    -2,
    "raider-return",
    "陈娅",
  ),
  node(
    "radio-request",
    "乔榆：有人在另一端吗",
    "取得黑岭中继台的接线方式。",
    "npc",
    "broadcast",
    -2,
    0,
    -2,
    "radio-request",
    "乔榆",
  ),
  node(
    "radio-repair",
    "修复黑岭中继台",
    "需要收发器一台、电子元件三个、蓄电池一块。",
    "terminal",
    "industry-7",
    -2,
    0,
    -2,
    "radio-repair",
  ),
  node(
    "radio-return",
    "和乔榆确认发送频率",
    "验证信号已经到达封锁线外。",
    "npc",
    "broadcast",
    -2,
    0,
    -2,
    "radio-return",
    "乔榆",
  ),
  node(
    "shelter-request",
    "许弥：地下还有灯",
    "十一位老人需要水泵恢复供水。",
    "npc",
    "city-3",
    0,
    0,
    -2,
    "shelter-request",
    "许弥",
  ),
  node(
    "shelter-power",
    "接通水库旧水泵",
    "需要两片净水片和一个电子元件。",
    "terminal",
    "lake-1",
    0,
    0,
    -2,
    "shelter-power",
  ),
  node(
    "shelter-return",
    "为避难所备用机加油",
    "需要一份燃料，完成持续供水。",
    "npc",
    "city-3",
    0,
    0,
    -2,
    "shelter-return",
    "许弥",
  ),
  node(
    "officer-request",
    "沈维：不删掉我的名字",
    "去医疗营房核实他的证词。",
    "npc",
    "fort-3",
    0,
    0,
    -2,
    "officer-request",
    "沈维",
  ),
  node(
    "officer-proof",
    "核验门外的叩击",
    "取回医疗营房的完整录音。",
    "terminal",
    "fort-7",
    0,
    0,
    -2,
    "officer-proof",
  ),
  node(
    "officer-return",
    "取得沈维签名证词",
    "取得可公开的证词与隔离阀编号。",
    "npc",
    "fort-3",
    0,
    0,
    -2,
    "officer-return",
    "沈维",
  ),
];

export const SIDE_QUESTS: SideQuestDefinition[] = [
  {
    id: "doctor",
    title: "没有回来的医生",
    synopsis: "找到被困矿场的医生，让病历重新有姓名。",
    steps: [
      { interaction: "doctor-request", objective: "在松谷诊所接受米拉的委托" },
      {
        interaction: "doctor-found",
        objective: "带绷带 ×2 前往矿场诊所救助韩医生",
        cost: { bandage: 2 },
      },
      { interaction: "doctor-return", objective: "把转院底单送回松谷诊所" },
    ],
    reward: { antibiotics: 2, firstaid: 1 },
    unlockRecipe: "narrative-field-kit",
  },
  {
    id: "hunter",
    title: "湖边的家人",
    synopsis: "用食物与消息连接一个被封锁线分开的家庭。",
    steps: [
      { interaction: "hunter-request", objective: "在钓鱼小屋与罗岚交谈" },
      {
        interaction: "hunter-route",
        objective: "带炖肉罐头 ×1、饮用水 ×1 前往林边住宅",
        cost: { cannedmeat: 1, water: 1 },
      },
      {
        interaction: "hunter-return",
        objective: "向钓鱼小屋的罗岚报告家人的路线",
      },
    ],
    reward: { fishingrod: 1, cookedfish: 2 },
    unlockRoute: "lakeside",
  },
  {
    id: "checkpoint",
    title: "没有发出的口粮",
    synopsis: "纠正一张伪造收据，让检查站的侧门重新打开。",
    steps: [
      { interaction: "checkpoint-request", objective: "在围墙哨所与阿衡交谈" },
      { interaction: "checkpoint-proof", objective: "去后勤仓库核验封条" },
      { interaction: "checkpoint-return", objective: "把封条带回围墙哨所" },
    ],
    reward: { vest: 1, beans: 2 },
    unlockRoute: "checkpoint",
  },
  {
    id: "raider",
    title: "一锅人的份量",
    synopsis: "用一份可维持的分水约定结束抢夺。",
    steps: [
      { interaction: "raider-request", objective: "在车站旅馆接受陈娅的请求" },
      {
        interaction: "raider-deal",
        objective: "带白豆罐头 ×2 去工业区值班宿舍谈判",
        cost: { beans: 2 },
      },
      {
        interaction: "raider-return",
        objective: "把滤芯和分水约定带回车站旅馆",
      },
    ],
    reward: { suppressor: 1, filter: 3 },
    unlockRoute: "underpass",
  },
  {
    id: "radio",
    title: "有人在另一端吗",
    synopsis: "让广播第一次传到封锁线外，而不是播放自己的回声。",
    steps: [
      { interaction: "radio-request", objective: "在北岭广播站与乔榆交谈" },
      {
        interaction: "radio-repair",
        objective: "用收发器 ×1、电子元件 ×3、蓄电池 ×1 修好黑岭中继台",
        cost: { radio: 1, electronics: 3, battery: 1 },
      },
      { interaction: "radio-return", objective: "回北岭广播站验证发送频率" },
    ],
    reward: { battery: 1 },
    unlockRecipe: "narrative-low-power-radio",
  },
  {
    id: "shelter",
    title: "地下还有灯",
    synopsis: "恢复十一位老人明早的饮水，准备可以长期值守的避难所。",
    steps: [
      { interaction: "shelter-request", objective: "在地铁入口与许弥交谈" },
      {
        interaction: "shelter-power",
        objective: "用净水片 ×2、电子元件 ×1 修复水库旧泵",
        cost: { filter: 2, electronics: 1 },
      },
      {
        interaction: "shelter-return",
        objective: "带燃料 ×1 回地铁入口启动备用机",
        cost: { fuel: 1 },
      },
    ],
    reward: { water: 4, filter: 2 },
    unlockRecipe: "narrative-water-cycle",
    unlockRoute: "shelter",
  },
  {
    id: "officer",
    title: "不删掉我的名字",
    synopsis: "核验一位军官的自白，接受他对自己责任的完整署名。",
    steps: [
      { interaction: "officer-request", objective: "在哨兵宿舍听取沈维的证词" },
      {
        interaction: "officer-proof",
        objective: "去医疗营房核验门外叩击的录音",
      },
      {
        interaction: "officer-return",
        objective: "回哨兵宿舍取得完整签名证词",
      },
    ],
    reward: { ammo556: 30, bandage: 3 },
  },
];
for (const quest of SIDE_QUESTS)
  quest.steps.forEach((step, stage) => {
    const entry = NARRATIVE_INTERACTIONS.find(
      (n) => n.id === step.interaction,
    )!;
    entry.questId = quest.id;
    entry.stage = stage;
  });

export const NARRATIVE_RECIPES: (Recipe & { unlockQuest: string })[] = [
  {
    id: "narrative-field-kit",
    name: "韩医生的野战急救包",
    description: "完成“没有回来的医生”后获得的节省耗材配方。",
    category: "医疗",
    station: "hand",
    ingredients: { bandage: 1, disinfectant: 1, cloth: 1 },
    output: "firstaid",
    count: 1,
    seconds: 5,
    unlockQuest: "doctor",
  },
  {
    id: "narrative-low-power-radio",
    name: "乔榆的低耗收发器",
    description: "完成中继修复后获得，减少精密元件消耗。",
    category: "工具机械",
    station: "workbench",
    ingredients: { electronics: 2, scrap: 2, parts: 1 },
    output: "radio",
    count: 1,
    seconds: 6,
    unlockQuest: "radio",
  },
  {
    id: "narrative-water-cycle",
    name: "避难所循环净水",
    description: "用一片净水片处理两份水；需要火源完成消毒。",
    category: "烹饪",
    station: "fire",
    ingredients: { dirtywater: 2, filter: 1 },
    output: "water",
    count: 2,
    seconds: 6,
    unlockQuest: "shelter",
  },
];
export const NARRATIVE_ROUTES = [
  {
    id: "lakeside",
    name: "三道斜杠巡林路",
    quest: "hunter",
    description: "许禾标记的林边住宅至湖岸路线，避开公路探照灯。",
    anchors: [
      anchor("pine-9", -15),
      anchor("lake-4", 18),
      anchor("lake-2", -12),
    ],
    doorId: null,
  },
  {
    id: "checkpoint",
    name: "检查站侧门",
    quest: "checkpoint",
    description: "阿衡打开围墙哨所的侧门，救援物资可以带出来。",
    anchors: [anchor("fort-6", 0, 0, -7), anchor("fort-5", 0, 0, -7)],
    doorId: "fort-6",
  },
  {
    id: "underpass",
    name: "旅馆—地铁停战通道",
    quest: "raider",
    description: "唐砾撤走地铁附近拦路队；感染者仍可能游荡。",
    anchors: [anchor("city-5", 0, 0, -8), anchor("city-3", 0, 0, -8)],
    doorId: "city-3",
  },
  {
    id: "shelter",
    name: "供水站—地下避难所",
    quest: "shelter",
    description: "避难所西门保持开启，水库与避难所形成物资路线。",
    anchors: [anchor("lake-1", 0, 0, -8), anchor("city-3", 0, 0, -8)],
    doorId: "city-3",
  },
] as const;
